In [21]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv("/Users/Prashant/My_Workspace/AI_ML/Krish_Naik/data/train.csv")

In [23]:
df.shape

(1460, 81)

In [24]:
df.size

118260

In [25]:
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [26]:
df = df.drop(columns=['Id'], errors = 'ignore')

In [27]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [28]:
missing = df.isnull().sum()

In [29]:
missing

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [30]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='str')

In [31]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [32]:
x = df.drop("SalePrice", axis=1)
y = df["SalePrice"]

In [33]:
print(x.shape)
print(y.shape)

(1460, 79)
(1460,)

In [39]:
x_numeric = x.select_dtypes(include="number")

In [40]:
x_numeric.shape

(1460, 36)

In [41]:
target_corr = x_numeric.corrwith(y)

In [42]:
target_corr

MSSubClass      -0.084284
LotFrontage      0.351799
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
MasVnrArea       0.477493
BsmtFinSF1       0.386420
BsmtFinSF2      -0.011378
BsmtUnfSF        0.214479
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
BsmtHalfBath    -0.016844
FullBath         0.560664
HalfBath         0.284108
BedroomAbvGr     0.168213
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageYrBlt      0.486362
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
OpenPorchSF      0.315856
EnclosedPorch   -0.128578
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
dtype: float64

In [43]:
target_corr.abs().sort_values()

BsmtFinSF2       0.011378
BsmtHalfBath     0.016844
MiscVal          0.021190
LowQualFinSF     0.025606
YrSold           0.028923
3SsnPorch        0.044584
MoSold           0.046432
OverallCond      0.077856
MSSubClass       0.084284
PoolArea         0.092404
ScreenPorch      0.111447
EnclosedPorch    0.128578
KitchenAbvGr     0.135907
BedroomAbvGr     0.168213
BsmtUnfSF        0.214479
BsmtFullBath     0.227122
LotArea          0.263843
HalfBath         0.284108
OpenPorchSF      0.315856
2ndFlrSF         0.319334
WoodDeckSF       0.324413
LotFrontage      0.351799
BsmtFinSF1       0.386420
Fireplaces       0.466929
MasVnrArea       0.477493
GarageYrBlt      0.486362
YearRemodAdd     0.507101
YearBuilt        0.522897
TotRmsAbvGrd     0.533723
FullBath         0.560664
1stFlrSF         0.605852
TotalBsmtSF      0.613581
GarageArea       0.623431
GarageCars       0.640409
GrLivArea        0.708624
OverallQual      0.790982
dtype: float64

In [44]:
target_corr[abs(target_corr)<0.1]

MSSubClass     -0.084284
OverallCond    -0.077856
BsmtFinSF2     -0.011378
LowQualFinSF   -0.025606
BsmtHalfBath   -0.016844
3SsnPorch       0.044584
PoolArea        0.092404
MiscVal        -0.021190
MoSold          0.046432
YrSold         -0.028923
dtype: float64

In [45]:
low_corr_feature = target_corr[abs(target_corr) < 0.1].index

In [46]:
low_corr_feature

Index(['MSSubClass', 'OverallCond', 'BsmtFinSF2', 'LowQualFinSF',
       'BsmtHalfBath', '3SsnPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold'],
      dtype='str')

In [47]:
len(low_corr_feature)

10

In [48]:
x = x.drop(columns = low_corr_feature)

In [49]:
x.shape

(1460, 69)

In [51]:
corr_matrix = x.select_dtypes(include="number").corr()

In [52]:
corr_matrix

,LotFrontage,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,ScreenPorch
LotFrontage,1.000000,0.426095,0.251646,0.123349,0.088866,0.193458,0.233633,0.132644,0.392075,0.457181,...,-0.006069,0.352096,0.266639,0.070250,0.285691,0.344997,0.088521,0.151972,0.010700,0.041383
LotArea,0.426095,1.000000,0.105806,0.014228,0.013788,0.104160,0.214103,-0.002618,0.260833,0.299475,...,-0.017784,0.190015,0.271364,-0.024947,0.154871,0.180403,0.171698,0.084774,-0.018340,0.043160
OverallQual,0.251646,0.105806,1.000000,0.572323,0.550684,0.411876,0.239666,0.308159,0.537808,0.476224,...,-0.183882,0.427452,0.396765,0.547766,0.600671,0.562022,0.238923,0.308819,-0.113937,0.064886
YearBuilt,0.123349,0.014228,0.572323,1.000000,0.592855,0.315707,0.249503,0.149040,0.391452,0.281986,...,-0.174800,0.095589,0.147716,0.825667,0.537850,0.478954,0.224880,0.188686,-0.387268,-0.050364
YearRemodAdd,0.088866,0.013788,0.550684,0.592855,1.000000,0.179618,0.128451,0.181133,0.291066,0.240379,...,-0.149598,0.191740,0.112581,0.642277,0.420622,0.371600,0.205726,0.226298,-0.193919,-0.038740
MasVnrArea,0.193458,0.104160,0.411876,0.315707,0.179618,1.000000,0.264736,0.114442,0.363936,0.344501,...,-0.037610,0.280682,0.249070,0.252691,0.364204,0.373066,0.159718,0.125703,-0.110204,0.061466
BsmtFinSF1,0.233633,0.214103,0.239666,0.249503,0.128451,0.264736,1.000000,-0.495251,0.522396,0.445863,...,-0.081007,0.044316,0.260011,0.153484,0.224054,0.296970,0.204306,0.111761,-0.102303,0.062021
BsmtUnfSF,0.132644,-0.002618,0.308159,0.149040,0.181133,0.114442,-0.495251,1.000000,0.415360,0.317987,...,0.030086,0.250647,0.051575,0.190708,0.214175,0.183303,-0.005316,0.129005,-0.002538,-0.012579
TotalBsmtSF,0.392075,0.260833,0.537808,0.391452,0.291066,0.363936,0.522396,0.415360,1.000000,0.819530,...,-0.068901,0.285573,0.339519,0.322445,0.434585,0.486665,0.232019,0.247264,-0.095478,0.084489
1stFlrSF,0.457181,0.299475,0.476224,0.281986,0.240379,0.344501,0.445863,0.317987,0.819530,1.000000,...,0.068101,0.409516,0.410531,0.233449,0.439317,0.489782,0.235459,0.211671,-0.065292,0.088758
2ndFlrSF,0.080177,0.050986,0.295493,0.010308,0.140024,0.174561,-0.137079,0.004469,-0.174512,-0.202646,...,0.059306,0.616423,0.194561,0.070832,0.183926,0.138347,0.092165,0.208026,0.061989,0.040606
GrLivArea,0.402797,0.263116,0.593007,0.199010,0.287389,0.390857,0.208171,0.240257,0.454868,0.566024,...,0.100063,0.825489,0.461679,0.231197,0.467247,0.468997,0.247433,0.330224,0.009113,0.101510
BsmtFullBath,0.100949,0.158155,0.111098,0.187599,0.119470,0.085310,0.649212,-0.422900,0.307351,0.244671,...,-0.041503,-0.053275,0.137928,0.124553,0.131881,0.179189,0.175315,0.067341,-0.049911,0.023148
FullBath,0.198769,0.126031,0.550600,0.468271,0.439046,0.276833,0.058543,0.288886,0.323722,0.380637,...,0.133115,0.554784,0.243671,0.484557,0.469672,0.405656,0.187703,0.259977,-0.115093,-0.008106
HalfBath,0.053532,0.014259,0.273458,0.242656,0.183331,0.201444,0.004262,-0.041118,-0.048804,-0.119916,...,-0.068263,0.343415,0.203649,0.196785,0.219178,0.163549,0.108080,0.199740,-0.095317,0.072426
BedroomAbvGr,0.263170,0.119690,0.101676,-0.070651,-0.040581,0.102821,-0.107355,0.166643,0.050450,0.127401,...,0.198597,0.676620,0.107570,-0.064518,0.086106,0.065253,0.046854,0.093810,0.041570,0.044300
KitchenAbvGr,-0.006069,-0.017784,-0.183882,-0.174800,-0.149598,-0.037610,-0.081007,0.030086,-0.068901,0.068101,...,1.000000,0.256045,-0.123936,-0.124411,-0.050634,-0.064433,-0.090130,-0.070091,0.037312,-0.051613
TotRmsAbvGrd,0.352096,0.190015,0.427452,0.095589,0.191740,0.280682,0.044316,0.250647,0.285573,0.409516,...,0.256045,1.000000,0.326114,0.148112,0.362289,0.337822,0.165984,0.234192,0.004151,0.059383
Fireplaces,0.266639,0.271364,0.396765,0.147716,0.112581,0.249070,0.260011,0.051575,0.339519,0.410531,...,-0.123936,0.326114,1.000000,0.046822,0.300789,0.269141,0.200019,0.169405,-0.024822,0.184530
GarageYrBlt,0.070250,-0.024947,0.547766,0.825667,0.642277,0.252691,0.153484,0.190708,0.322445,0.233449,...,-0.124411,0.148112,0.046822,1.000000,0.588920,0.564567,0.224577,0.228425,-0.297003,-0.075418
GarageCars,0.285691,0.154871,0.600671,0.537850,0.420622,0.364204,0.224054,0.214175,0.434585,0.439317,...,-0.050634,0.362289,0.300789,0.588920,1.000000,0.882475,0.226342,0.213569,-0.151434,0.050494
GarageArea,0.344997,0.180403,0.562022,0.478954,0.371600,0.373066,0.296970,0.183303,0.486665,0.489782,...,-0.064433,0.337822,0.269141,0.564567,0.882475,1.000000,0.224666,0.241435,-0.121777,0.051412
WoodDeckSF,0.088521,0.171698,0.238923,0.224880,0.205726,0.159718,0.204306,-0.005316,0.232019,0.235459,...,-0.090130,0.165984,0.200019,0.224577,0.226342,0.224666,1.000000,0.058661,-0.125989,-0.074181
OpenPorchSF,0.151972,0.084774,0.308819,0.188686,0.226298,0.125703,0.111761,0.129005,0.247264,0.211671,...,-0.070091,0.234192,0.169405,0.228425,0.213569,0.241435,0.058661,1.000000,-0.093079,0.074304
EnclosedPorch,0.010700,-0.018340,-0.113937,-0.387268,-0.193919,-0.110204,-0.102303,-0.002538,-0.095478,-0.065292,...,0.037312,0.004151,-0.024822,-0.297003,-0.151434,-0.121777,-0.125989,-0.093079,1.000000,-0.082864
ScreenPorch,0.041383,0.043160,0.064886,-0.050364,-0.038740,0.061466,0.062021,-0.012579,0.084489,0.088758,...,-0.051613,0.059383,0.184530,-0.075418,0.050494,0.051412,-0.074181,0.074304,-0.082864,1.000000

In [53]:
corr_matrix = x.select_dtypes(include="number").corr()

In [54]:
corr_matrix

,LotFrontage,LotArea,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,ScreenPorch
LotFrontage,1.000000,0.426095,0.251646,0.123349,0.088866,0.193458,0.233633,0.132644,0.392075,0.457181,...,-0.006069,0.352096,0.266639,0.070250,0.285691,0.344997,0.088521,0.151972,0.010700,0.041383
LotArea,0.426095,1.000000,0.105806,0.014228,0.013788,0.104160,0.214103,-0.002618,0.260833,0.299475,...,-0.017784,0.190015,0.271364,-0.024947,0.154871,0.180403,0.171698,0.084774,-0.018340,0.043160
OverallQual,0.251646,0.105806,1.000000,0.572323,0.550684,0.411876,0.239666,0.308159,0.537808,0.476224,...,-0.183882,0.427452,0.396765,0.547766,0.600671,0.562022,0.238923,0.308819,-0.113937,0.064886
YearBuilt,0.123349,0.014228,0.572323,1.000000,0.592855,0.315707,0.249503,0.149040,0.391452,0.281986,...,-0.174800,0.095589,0.147716,0.825667,0.537850,0.478954,0.224880,0.188686,-0.387268,-0.050364
YearRemodAdd,0.088866,0.013788,0.550684,0.592855,1.000000,0.179618,0.128451,0.181133,0.291066,0.240379,...,-0.149598,0.191740,0.112581,0.642277,0.420622,0.371600,0.205726,0.226298,-0.193919,-0.038740
MasVnrArea,0.193458,0.104160,0.411876,0.315707,0.179618,1.000000,0.264736,0.114442,0.363936,0.344501,...,-0.037610,0.280682,0.249070,0.252691,0.364204,0.373066,0.159718,0.125703,-0.110204,0.061466
BsmtFinSF1,0.233633,0.214103,0.239666,0.249503,0.128451,0.264736,1.000000,-0.495251,0.522396,0.445863,...,-0.081007,0.044316,0.260011,0.153484,0.224054,0.296970,0.204306,0.111761,-0.102303,0.062021
BsmtUnfSF,0.132644,-0.002618,0.308159,0.149040,0.181133,0.114442,-0.495251,1.000000,0.415360,0.317987,...,0.030086,0.250647,0.051575,0.190708,0.214175,0.183303,-0.005316,0.129005,-0.002538,-0.012579
TotalBsmtSF,0.392075,0.260833,0.537808,0.391452,0.291066,0.363936,0.522396,0.415360,1.000000,0.819530,...,-0.068901,0.285573,0.339519,0.322445,0.434585,0.486665,0.232019,0.247264,-0.095478,0.084489
1stFlrSF,0.457181,0.299475,0.476224,0.281986,0.240379,0.344501,0.445863,0.317987,0.819530,1.000000,...,0.068101,0.409516,0.410531,0.233449,0.439317,0.489782,0.235459,0.211671,-0.065292,0.088758
2ndFlrSF,0.080177,0.050986,0.295493,0.010308,0.140024,0.174561,-0.137079,0.004469,-0.174512,-0.202646,...,0.059306,0.616423,0.194561,0.070832,0.183926,0.138347,0.092165,0.208026,0.061989,0.040606
GrLivArea,0.402797,0.263116,0.593007,0.199010,0.287389,0.390857,0.208171,0.240257,0.454868,0.566024,...,0.100063,0.825489,0.461679,0.231197,0.467247,0.468997,0.247433,0.330224,0.009113,0.101510
BsmtFullBath,0.100949,0.158155,0.111098,0.187599,0.119470,0.085310,0.649212,-0.422900,0.307351,0.244671,...,-0.041503,-0.053275,0.137928,0.124553,0.131881,0.179189,0.175315,0.067341,-0.049911,0.023148
FullBath,0.198769,0.126031,0.550600,0.468271,0.439046,0.276833,0.058543,0.288886,0.323722,0.380637,...,0.133115,0.554784,0.243671,0.484557,0.469672,0.405656,0.187703,0.259977,-0.115093,-0.008106
HalfBath,0.053532,0.014259,0.273458,0.242656,0.183331,0.201444,0.004262,-0.041118,-0.048804,-0.119916,...,-0.068263,0.343415,0.203649,0.196785,0.219178,0.163549,0.108080,0.199740,-0.095317,0.072426
BedroomAbvGr,0.263170,0.119690,0.101676,-0.070651,-0.040581,0.102821,-0.107355,0.166643,0.050450,0.127401,...,0.198597,0.676620,0.107570,-0.064518,0.086106,0.065253,0.046854,0.093810,0.041570,0.044300
KitchenAbvGr,-0.006069,-0.017784,-0.183882,-0.174800,-0.149598,-0.037610,-0.081007,0.030086,-0.068901,0.068101,...,1.000000,0.256045,-0.123936,-0.124411,-0.050634,-0.064433,-0.090130,-0.070091,0.037312,-0.051613
TotRmsAbvGrd,0.352096,0.190015,0.427452,0.095589,0.191740,0.280682,0.044316,0.250647,0.285573,0.409516,...,0.256045,1.000000,0.326114,0.148112,0.362289,0.337822,0.165984,0.234192,0.004151,0.059383
Fireplaces,0.266639,0.271364,0.396765,0.147716,0.112581,0.249070,0.260011,0.051575,0.339519,0.410531,...,-0.123936,0.326114,1.000000,0.046822,0.300789,0.269141,0.200019,0.169405,-0.024822,0.184530
GarageYrBlt,0.070250,-0.024947,0.547766,0.825667,0.642277,0.252691,0.153484,0.190708,0.322445,0.233449,...,-0.124411,0.148112,0.046822,1.000000,0.588920,0.564567,0.224577,0.228425,-0.297003,-0.075418
GarageCars,0.285691,0.154871,0.600671,0.537850,0.420622,0.364204,0.224054,0.214175,0.434585,0.439317,...,-0.050634,0.362289,0.300789,0.588920,1.000000,0.882475,0.226342,0.213569,-0.151434,0.050494
GarageArea,0.344997,0.180403,0.562022,0.478954,0.371600,0.373066,0.296970,0.183303,0.486665,0.489782,...,-0.064433,0.337822,0.269141,0.564567,0.882475,1.000000,0.224666,0.241435,-0.121777,0.051412
WoodDeckSF,0.088521,0.171698,0.238923,0.224880,0.205726,0.159718,0.204306,-0.005316,0.232019,0.235459,...,-0.090130,0.165984,0.200019,0.224577,0.226342,0.224666,1.000000,0.058661,-0.125989,-0.074181
OpenPorchSF,0.151972,0.084774,0.308819,0.188686,0.226298,0.125703,0.111761,0.129005,0.247264,0.211671,...,-0.070091,0.234192,0.169405,0.228425,0.213569,0.241435,0.058661,1.000000,-0.093079,0.074304
EnclosedPorch,0.010700,-0.018340,-0.113937,-0.387268,-0.193919,-0.110204,-0.102303,-0.002538,-0.095478,-0.065292,...,0.037312,0.004151,-0.024822,-0.297003,-0.151434,-0.121777,-0.125989,-0.093079,1.000000,-0.082864
ScreenPorch,0.041383,0.043160,0.064886,-0.050364,-0.038740,0.061466,0.062021,-0.012579,0.084489,0.088758,...,-0.051613,0.059383,0.184530,-0.075418,0.050494,0.051412,-0.074181,0.074304,-0.082864,1.000000

In [55]:
corr_matrix.abs().unstack().sort_values(ascending=False)

LotFrontage    LotFrontage      1.000000
FullBath       FullBath         1.000000
YearBuilt      YearBuilt        1.000000
YearRemodAdd   YearRemodAdd     1.000000
MasVnrArea     MasVnrArea       1.000000
                                  ...
EnclosedPorch  TotRmsAbvGrd     0.004151
BsmtUnfSF      LotArea          0.002618
LotArea        BsmtUnfSF        0.002618
BsmtUnfSF      EnclosedPorch    0.002538
EnclosedPorch  BsmtUnfSF        0.002538
Length: 676, dtype: float64

In [56]:
high_corr = corr_matrix.abs().unstack().sort_values(ascending=False)
high_corr[(high_corr < 1) & (high_corr > 0.8)]

GarageArea    GarageCars      0.882475
GarageCars    GarageArea      0.882475
YearBuilt     GarageYrBlt     0.825667
GarageYrBlt   YearBuilt       0.825667
TotRmsAbvGrd  GrLivArea       0.825489
GrLivArea     TotRmsAbvGrd    0.825489
1stFlrSF      TotalBsmtSF     0.819530
TotalBsmtSF   1stFlrSF        0.819530
dtype: float64

In [57]:
df.isnull().sum()

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [58]:
missing = df.isnull().mean() * 100
missing[missing > 0]

LotFrontage     17.739726
Alley           93.767123
MasVnrType      59.726027
MasVnrArea       0.547945
BsmtQual         2.534247
BsmtCond         2.534247
BsmtExposure     2.602740
BsmtFinType1     2.534247
BsmtFinType2     2.602740
Electrical       0.068493
FireplaceQu     47.260274
GarageType       5.547945
GarageYrBlt      5.547945
GarageFinish     5.547945
GarageQual       5.547945
GarageCond       5.547945
PoolQC          99.520548
Fence           80.753425
MiscFeature     96.301370
dtype: float64

In [59]:
df["LotFrontage"].mean()

np.float64(70.04995836802665)

In [60]:
df["LotFrontage"].median()

np.float64(69.0)

In [61]:
df["LotFrontage"] = df["LotFrontage"].fillna(df["LotFrontage"].median())

In [62]:
df["LotFrontage"].isnull().sum()

np.int64(0)